---
final_name: app-autoscaler
min_cli_version: 1.5.0.pre.1001
blobstore:
  provider: s3
  options:
    bucket_name: app-autoscaler-blobs
    region: us-geo
    host: s3-api.us-geo.objectstorage.softlayer.net
